### ISSUE TITLE
Add option to save result to variable

### ISSUE THREAD

**Issue by Gabryxx7** [OmbraDiFenice/table2csv#10]
Hi,

I realised it can be a bit hard to save the output to an HTML element and then get it back. Also considering possible encoding/decoding issues.
In some cases it might just be faster to save the output to a variable, adding an option like this to the switch:

```javascript
    switch (action) {
      case "download":
        csv = convert(table);
        download(options.filename, csv);
        break;

        case "output":
          csv = convert(table);
          $(options.appendTo).append($("<pre>").text(csv));
          break;

       //New case
        case "variable":
          return(convert(table));
          break;

      default:
        throw new Error("\"action\" argument must be one of the supported action strings");
    }
```

**Comment by OmbraDiFenice** [comment]
Thank you for the suggestion 😃 This feature was merged with PR #11 

Beware though that when using this action you will no longer be able to chain the call `table2csv()` to any other jQuery method. Of course this should not be a problem, since if you want (and expect) to have the value returned by the call it means you are not performing any chaining anyway.
