### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by justjess678** [OmbraDiFenice/table2csv#7]
I've been trying to use this library on a very simple project but it refuses to be imported correctly, and doesn't seem to conform to today's standards of import (requiring jQuery import too etc)

My code (about.html):

`<html>
  <head>
    <meta charset="utf-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/table2csv@1.1.3/src/table2csv.min.js"></script>
    
    <script>function exportCSV(){
        document.getElementById("rep").innerHTML = "NOK";
        var csv = document.getElementById('fullDataTable').table2csv();
        window.location.href = 'data:text/csv;charset=UTF-8,'+ encodeURIComponent(csv);
        document.getElementById("rep").innerHTML = "OK";
    }
    </script>
</head>
<body>
    <table id="fullDataTable">
        <thead>
            <tr>
              <th>Foo.</th>
              <th>bar.</th>
              <th>bla.</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>2</td>
                <td>3</td>
            </tr>
        </tbody>
    </table>
    <button onclick="exportCSV()">DOWNLOAD</button><br>
    <p id="rep"></p>
</body>
</html>`

The errors:

`Uncaught SyntaxError: Unexpected token <   table2csv.min.js:1`
`Uncaught TypeError: document.getElementById(...).table2csv is not a function
at exportCSV (about:11)
at HTMLButtonElement.onclick (about:34)`

More info and updates on my issue [here](https://stackoverflow.com/questions/54310393/call-local-js-package-with-nodejs-npm)

**Comment by OmbraDiFenice** [comment]
This is a jQuery plugin meant to be used in web pages. As far as I know (but I could be a bit rusty on this), the way to use jQuery plugin is to first import jQuery in the page and then import the files of the plugin. This is needed because a jQuery plugin is built (or "registered", if you like) by calling a jQuery method which hooks up the plugin code into jQuery itself.

This also leads to your second problem: any jQuery plugin will work on *jQuery objects*, which are in fact javascript objects wrapping around the standard DOM objects. In your case you're trying to access the `table2csv()` on the result of `document.getElementById()`, which returns a standard DOM object, not a jQuery object. Of course, this standard object will not have any of the extra methods provided by jQuery, hence your "table2csv is not a function" error.

Finally, note that currently the call to `table2csv()` is not returning anything; it either start the download of a file or appends the generated csv to the text content of another jQuery object. Your assignment to the `csv` variable is therefore useless and will not have the behavior you probably expect.
